gsm_lot_user:
    resource: "@GsmLotUserBundle/Controller/"
    type:     annotation
    prefix:   /

gsm_lot_subscription:
    resource: "@GsmLotSubscriptionBundle/Controller/"
    type:     annotation
    prefix:   /

gsm_lot_product:
    resource: "@GsmLotProductBundle/Controller/"
    type:     annotation
    prefix:   /

gsm_lot_mail_box:
    resource: "@GsmLotMailBoxBundle/Controller/"
    type:     annotation
    prefix:   /

gsm_lot_trader:
    resource: "@GsmLotTraderBundle/Controller/"
    type:     annotation
    prefix:   /

#routing du module fosuer
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"