gsm_lot_index:
    resource: GsmLot\IndexBundle\Controller\IndexController
    type:     annotation
    prefix:   /

gsm_lot_index_mobile:
    resource: GsmLot\IndexBundle\Controller\OfferFrontController
    type:     annotation
    prefix:   /mobile

gms_lot_offer_model:
    resource: GsmLot\OfferBundle\Controller\ModelController
    type: annotation
    prefix: /model

gsm_lot_user:
    resource: "@GsmLotUserBundle/Controller/"
    type:     annotation
    prefix:   /user

gsm_lot_subscription:
    resource: "@GsmLotSubscriptionBundle/Controller/"
    type:     annotation
    prefix:   /subscription

gsm_lot_product:
    resource: "@GsmLotOfferBundle/Controller/"
    type:     annotation
    prefix:   /offer

gsm_lot_mail_box:
    resource: "@GsmLotMailBoxBundle/Controller/"
    type:     annotation
    prefix:   /mailbox

gsm_lot_trader:
    resource: "@GsmLotTraderBundle/Controller/"
    type:     annotation
    prefix:   /trader

#routing du module fosuer
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#routing js routing bundle
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"